/**
 * CPMAnchorsDefault.h — GENERATED by tools/cpm_anchors.py. Do not edit.
 *
 * source: Resources/cpm_ui_anchors.json  (sha256 29b4ebb843524b6f05f1fec1e82b9c175325cfc37d45268f5c7132be80ac4d05)
 * calibration id: cpm_landscape_reference_unverified   reference screen: 844 x 390 pt   landscape: yes
 *
 * Coordinates are points on the *reference* device, origin top-left, y down.
 * CPMUICalibration scales them onto the real screen; the on-screen ROI editor
 * overrides them per device. Regenerate with: make anchors
 */
#ifndef CPM_ANCHORS_DEFAULT_H
#define CPM_ANCHORS_DEFAULT_H

#import <CoreGraphics/CoreGraphics.h>
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/* `type` mirrors CPMUIElementType (defined in CPMUICalibration.h) as a plain
 * integer so this header stays includable in both directions. */

typedef struct {
    NSInteger type;
    CGFloat centerX, centerY;      /* reference points */
    CGFloat width, height;
    CGFloat sliderMinX, sliderMaxX;  /* track ends, reference points */
    CGFloat sliderMinY, sliderMaxY;
    BOOL isSlider;
    BOOL isValid;
    const char *name;
} CPMUIAnchorRecord;

#define CPM_ANCHOR_REFERENCE_WIDTH  844.0
#define CPM_ANCHOR_REFERENCE_HEIGHT 390.0
#define CPM_ANCHOR_IS_LANDSCAPE     1
#define CPM_ANCHOR_CALIBRATION_ID   @"cpm_landscape_reference_unverified"
#define CPM_ANCHOR_SOURCE_SHA256    @"29b4ebb843524b6f05f1fec1e82b9c175325cfc37d45268f5c7132be80ac4d05"
#define CPM_ANCHOR_RECORD_COUNT     13u

#define CPM_ANCHOR_HAS_CANVAS_RECT  1
#define CPM_ANCHOR_CANVAS_RECT      CGRectMake(190, 24, 430, 330)

static const CPMUIAnchorRecord CPMUIAnchorRecords[CPM_ANCHOR_RECORD_COUNT]
    __attribute__((unused)) = {
    { CPMUIElementTypeAddShape, 806.000, 44.000, 60.000, 60.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Add Shape  (VinylsEditor: CreateSticker)" },
    { CPMUIElementTypeShapeSelector, 70.000, 196.000, 124.000, 300.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Shape Selector  (VinylsEditorUI.stickersWidget)" },
    { CPMUIElementTypeColorPicker, 776.000, 120.000, 72.000, 72.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Color Picker  (VinylsEditor.ChangeColor)" },
    { CPMUIElementTypeRedSlider, 730.000, 184.000, 200.000, 22.000, 630.000, 830.000, 184.000, 184.000, YES, YES, "Red Slider" },
    { CPMUIElementTypeGreenSlider, 730.000, 216.000, 200.000, 22.000, 630.000, 830.000, 216.000, 216.000, YES, YES, "Green Slider" },
    { CPMUIElementTypeBlueSlider, 730.000, 248.000, 200.000, 22.000, 630.000, 830.000, 248.000, 248.000, YES, YES, "Blue Slider" },
    { CPMUIElementTypeScaleSlider, 730.000, 296.000, 200.000, 22.000, 630.000, 830.000, 296.000, 296.000, YES, YES, "Scale Slider  (scaleSlider/scaleX)" },
    { CPMUIElementTypeRotateSlider, 730.000, 328.000, 200.000, 22.000, 630.000, 830.000, 328.000, 328.000, YES, YES, "Rotate Slider  (rotationSlider)" },
    { CPMUIElementTypeMoveJoystick, 300.000, 320.000, 96.000, 96.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Move Joystick  (JoystickNGUI, joystickSlider)" },
    { CPMUIElementTypeConfirmButton, 780.000, 364.000, 96.000, 44.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Confirm  (SaveVinyl)" },
    { CPMUIElementTypeCancelButton, 664.000, 364.000, 96.000, 44.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Cancel  (CleanStuff)" },
    { CPMUIElementTypeLayerListView, 24.000, 196.000, 44.000, 300.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Layer List  (stickersScrollBar)" },
    { CPMUIElementTypeZoomControl, 600.000, 44.000, 96.000, 40.000, 0.000, 0.000, 0.000, 0.000, NO, YES, "Zoom  (zoomSlider)" },
};

NS_ASSUME_NONNULL_END

#endif /* CPM_ANCHORS_DEFAULT_H */
