/**
 * CPMGameLayout.m -- generated by tools/cpm_il2cpp.py - DO NOT EDIT.
 *
 * Source: dump.cs sha256=75d42adc05b0248a (25357907 bytes).
 * Regenerate with: make layout
 */
#import "CPMGameLayout.h"

#import <Foundation/Foundation.h>

typedef struct {
    CPMGameClassID id;
    const char *className;
    const char *namesp;
    const char *assembly;
    NSInteger typedefIndex;
} CPMGameClassRecord;

static const CPMGameClassRecord CPMGameClassTable[16] = {
    [0] = { CPMGameClassVinylsEditor, "VinylsEditor", "", "", 5173 },
    [1] = { CPMGameClassVinylDrawer, "VinylDrawer", "", "", 5171 },
    [2] = { CPMGameClassVinylContainer, "VinylContainer", "", "", 5170 },
    [3] = { CPMGameClassVinylsEditorUI, "VinylsEditorUI", "", "", 5177 },
    [4] = { CPMGameClassStickerItem, "StickerItem", "", "Assembly-CSharp.dll", 841 },
    [5] = { CPMGameClassSelectSticker, "SelectSticker", "", "Assembly-CSharp.dll", 832 },
    [6] = { CPMGameClassMoveSliderToTarget, "MoveSliderToTarget", "", "Assembly-CSharp.dll", 854 },
    [7] = { CPMGameClassJoystickNGUI, "JoystickNGUI", "", "Assembly-CSharp.dll", 193 },
    [8] = { CPMGameClassUISlider, "UISlider", "", "NGUI.dll", 65 },
    [9] = { CPMGameClassUIInput, "UIInput", "", "NGUI.dll", 201 },
    [10] = { CPMGameClassVinylData, "VinylData", "", "", 1922 },
    [11] = { CPMGameClassOneVynil, "OneVynil", "", "", 5096 },
    [12] = { CPMGameClassUnityObject, "Object", "", "", 368 },
    [13] = { CPMGameClassGameObject, "GameObject", "", "", 340 },
    [14] = { CPMGameClassList1, "List`1", "", "", 1612 },
    [15] = { CPMGameClassDictionary2, "Dictionary`2", "", "", 1592 },
};

const CPMGameFieldRecord CPMGameFieldTable[CPMGameFieldCount] = {
    [0] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorSideCheckParent, 0x50u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "sideCheckParent", "Transform" },
    [1] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleQuad, 0x58u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleQuad", "GameObject" },
    [2] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorZoomSlider, 0x70u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "zoomSlider", "MoveSliderToTarget" },
    [3] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorRotationSlider, 0x78u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "rotationSlider", "MoveSliderToTarget" },
    [4] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleSliderX, 0x80u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleSliderX", "MoveSliderToTarget" },
    [5] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleSliderY, 0x88u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleSliderY", "MoveSliderToTarget" },
    [6] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleSlider, 0x90u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleSlider", "MoveSliderToTarget" },
    [7] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorJoystickSlider, 0x98u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "joystickSlider", "MoveSliderToTarget" },
    [8] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorJoystickUI, 0xA0u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "joystickUI", "JoystickNGUI" },
    [9] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorStickersScrollBar, 0xB8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "stickersScrollBar", "UIScrollBar" },
    [10] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorStickersScrollView, 0xC0u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "stickersScrollView", "UIScrollView" },
    [11] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorVinylsCountLabel, 0xC8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "vinylsCountLabel", "UILabel" },
    [12] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorEditUI, 0xE8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "editUI", "GameObject" },
    [13] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorStickersWidget, 0xF8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "stickersWidget", "GameObject" },
    [14] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorVinylTransformEditPanel, 0x170u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "VinylTransformEditPanel", "GameObject" },
    [15] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorAngleInputField, 0x178u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "AngleInputField", "UIInput" },
    [16] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleXInputField, 0x180u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "ScaleXInputField", "UIInput" },
    [17] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleYInputField, 0x188u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "ScaleYInputField", "UIInput" },
    [18] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorAngleText, 0x1A8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "angleText", "UILabel" },
    [19] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleXText, 0x1B0u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleXText", "UILabel" },
    [20] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorScaleYText, 0x1B8u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "scaleYText", "UILabel" },
    [21] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorEditorUI, 0x1D0u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_editorUI", "VinylsEditorUI" },
    [22] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentVinyl, 0x1E0u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_currentVinyl", "GameObject" },
    [23] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentVinylsType, 0x1F8u, 1, CPMGameValueKindUInt8, 0, "VinylsEditor", "_currentVinylsType", "VinylsType" },
    [24] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentOperation, 0x1F9u, 1, CPMGameValueKindUInt8, 0, "VinylsEditor", "_currentOperation", "VinylsEditorOperation" },
    [25] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentStickersParent, 0x200u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_currentStickersParent", "Transform" },
    [26] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentSticker, 0x210u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_currentSticker", "StickerItem" },
    [27] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorCurrentPivotTransform, 0x218u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_currentPivotTransform", "Transform" },
    [28] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorLastVinylOrder, 0x23Cu, 4, CPMGameValueKindInt32, 0, "VinylsEditor", "_lastVinylOrder", "int" },
    [29] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorIsEditingExisting, 0x248u, 1, CPMGameValueKindBool, 0, "VinylsEditor", "_isEditingExisting", "bool" },
    [30] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorIsMerged, 0x249u, 1, CPMGameValueKindBool, 0, "VinylsEditor", "_isMerged", "bool" },
    [31] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorSaved, 0x24Au, 1, CPMGameValueKindBool, 0, "VinylsEditor", "_saved", "bool" },
    [32] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorAllStickers, 0x258u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_allStickers", "List<StickerItem>" },
    [33] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorEditingStickers, 0x260u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_editingStickers", "List<StickerItem>" },
    [34] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorGroupParent, 0x270u, 8, CPMGameValueKindObject, 0, "VinylsEditor", "_groupParent", "Transform" },
    [35] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorIsDragging, 0x278u, 1, CPMGameValueKindBool, 0, "VinylsEditor", "_isDragging", "bool" },
    [36] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorRenderDirty, 0x2D0u, 1, CPMGameValueKindBool, 0, "VinylsEditor", "_renderDirty", "bool" },
    [37] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorVinylsTypeId, 0x2F4u, 4, CPMGameValueKindInt32, 0, "VinylsEditor", "_vinylsTypeId", "int" },
    [38] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorMaxVinylsCount, 0x2F8u, 4, CPMGameValueKindInt32, 0, "VinylsEditor", "_maxVinylsCount", "int" },
    [39] = { CPMGameClassVinylsEditor, CPMGameFieldVinylsEditorHasVinyl, 0x0u, 1, CPMGameValueKindBool, 1, "VinylsEditor", "<HasVinyl>k__BackingField", "bool" },
    [40] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerCamera, 0x20u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_camera", "Camera" },
    [41] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerVinylPrefab, 0x28u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_vinylPrefab", "GameObject" },
    [42] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerVinylPrefabFonts, 0x30u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_vinylPrefabFonts", "GameObject[]" },
    [43] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerContainer, 0x38u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_container", "VinylContainer" },
    [44] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerPlaneMaterial, 0x40u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_planeMaterial", "Material" },
    [45] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerFactory, 0x48u, 8, CPMGameValueKindObject, 0, "VinylDrawer", "_factory", "IPrefabFactory" },
    [46] = { CPMGameClassVinylDrawer, CPMGameFieldVinylDrawerInstance, 0x0u, 8, CPMGameValueKindObject, 1, "VinylDrawer", "_instance", "VinylDrawer" },
    [47] = { CPMGameClassVinylContainer, CPMGameFieldVinylContainerVinylsHolders, 0x20u, 8, CPMGameValueKindObject, 0, "VinylContainer", "_vinylsHolders", "Dictionary<VinylsType, VinylsContext>" },
    [48] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIEditPlane, 0x10u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "editPlane", "GameObject" },
    [49] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIVisualIcons, 0x18u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "visualIcons", "GameObject" },
    [50] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIPosCollider, 0x20u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "posCollider", "Transform" },
    [51] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIRotCollider, 0x28u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "rotCollider", "Transform" },
    [52] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIScaleCollider, 0x30u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "scaleCollider", "Transform" },
    [53] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIPosIcon, 0x38u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "posIcon", "Transform" },
    [54] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIRotIcon, 0x40u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "rotIcon", "Transform" },
    [55] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIScaleIcon, 0x48u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "scaleIcon", "Transform" },
    [56] = { CPMGameClassVinylsEditorUI, CPMGameFieldVinylsEditorUIMiddlePoint, 0x50u, 8, CPMGameValueKindObject, 0, "VinylsEditorUI", "middlePoint", "Transform" },
    [57] = { CPMGameClassStickerItem, CPMGameFieldStickerItemTexture, 0x20u, 8, CPMGameValueKindObject, 0, "StickerItem", "texture", "UI2DSprite" },
    [58] = { CPMGameClassStickerItem, CPMGameFieldStickerItemSprite, 0x28u, 8, CPMGameValueKindObject, 0, "StickerItem", "sprite", "UI2DSprite" },
    [59] = { CPMGameClassStickerItem, CPMGameFieldStickerItemOrder, 0x30u, 4, CPMGameValueKindInt32, 0, "StickerItem", "Order", "int" },
    [60] = { CPMGameClassStickerItem, CPMGameFieldStickerItemStckerIndex, 0x34u, 4, CPMGameValueKindInt32, 0, "StickerItem", "stckerIndex", "int" },
    [61] = { CPMGameClassStickerItem, CPMGameFieldStickerItemPosition, 0x38u, 12, CPMGameValueKindVector3, 0, "StickerItem", "position", "Vector3" },
    [62] = { CPMGameClassStickerItem, CPMGameFieldStickerItemPositionIcon, 0x44u, 12, CPMGameValueKindVector3, 0, "StickerItem", "positionIcon", "Vector3" },
    [63] = { CPMGameClassStickerItem, CPMGameFieldStickerItemEuler, 0x50u, 12, CPMGameValueKindVector3, 0, "StickerItem", "euler", "Vector3" },
    [64] = { CPMGameClassStickerItem, CPMGameFieldStickerItemScale, 0x5Cu, 12, CPMGameValueKindVector3, 0, "StickerItem", "scale", "Vector3" },
    [65] = { CPMGameClassStickerItem, CPMGameFieldStickerItemColor, 0x70u, 16, CPMGameValueKindColor, 0, "StickerItem", "_color", "Color" },
    [66] = { CPMGameClassStickerItem, CPMGameFieldStickerItemThisVinyl, 0x80u, 8, CPMGameValueKindObject, 0, "StickerItem", "ThisVinyl", "Transform" },
    [67] = { CPMGameClassStickerItem, CPMGameFieldStickerItemYAngle, 0x90u, 4, CPMGameValueKindFloat, 0, "StickerItem", "yAngle", "float" },
    [68] = { CPMGameClassStickerItem, CPMGameFieldStickerItemXAngle, 0x94u, 4, CPMGameValueKindFloat, 0, "StickerItem", "xAngle", "float" },
    [69] = { CPMGameClassStickerItem, CPMGameFieldStickerItemFlipX, 0x98u, 4, CPMGameValueKindInt32, 0, "StickerItem", "flipX", "int" },
    [70] = { CPMGameClassStickerItem, CPMGameFieldStickerItemInitialColorBackround, 0x9Cu, 16, CPMGameValueKindColor, 0, "StickerItem", "InitialColorBackround", "Color" },
    [71] = { CPMGameClassStickerItem, CPMGameFieldStickerItemIsText, 0xACu, 1, CPMGameValueKindBool, 0, "StickerItem", "isText", "bool" },
    [72] = { CPMGameClassStickerItem, CPMGameFieldStickerItemText, 0xB0u, 8, CPMGameValueKindString, 0, "StickerItem", "text", "string" },
    [73] = { CPMGameClassStickerItem, CPMGameFieldStickerItemFontIndex, 0xB8u, 4, CPMGameValueKindInt32, 0, "StickerItem", "fontIndex", "int" },
    [74] = { CPMGameClassStickerItem, CPMGameFieldStickerItemItalic, 0xBCu, 1, CPMGameValueKindBool, 0, "StickerItem", "italic", "bool" },
    [75] = { CPMGameClassStickerItem, CPMGameFieldStickerItemBold, 0xBDu, 1, CPMGameValueKindBool, 0, "StickerItem", "bold", "bool" },
    [76] = { CPMGameClassStickerItem, CPMGameFieldStickerItemOldIndex, 0xE0u, 4, CPMGameValueKindInt32, 0, "StickerItem", "oldIndex", "int" },
    [77] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerIdText, 0x20u, 8, CPMGameValueKindObject, 0, "SelectSticker", "IdText", "UILabel" },
    [78] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerGeneralControl, 0x28u, 8, CPMGameValueKindObject, 0, "SelectSticker", "_generalControl", "GeneralControl" },
    [79] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerVinylsEditor, 0x30u, 8, CPMGameValueKindObject, 0, "SelectSticker", "_vinylsEditor", "VinylsEditor" },
    [80] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerStickerSelected, 0x38u, 4, CPMGameValueKindInt32, 0, "SelectSticker", "StickerSelected", "Action<int>" },
    [81] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerStickerIndex, 0x40u, 4, CPMGameValueKindInt32, 0, "SelectSticker", "<StickerIndex>k__BackingField", "int" },
    [82] = { CPMGameClassSelectSticker, CPMGameFieldSelectStickerSelectWheelCts, 0x48u, 8, CPMGameValueKindObject, 0, "SelectSticker", "_selectWheelCts", "CancellationTokenSource" },
    [83] = { CPMGameClassMoveSliderToTarget, CPMGameFieldMoveSliderToTargetTarget, 0x20u, 4, CPMGameValueKindFloat, 0, "MoveSliderToTarget", "target", "float" },
    [84] = { CPMGameClassMoveSliderToTarget, CPMGameFieldMoveSliderToTargetSpeed, 0x24u, 4, CPMGameValueKindFloat, 0, "MoveSliderToTarget", "speed", "float" },
    [85] = { CPMGameClassMoveSliderToTarget, CPMGameFieldMoveSliderToTargetSlider, 0x28u, 8, CPMGameValueKindObject, 0, "MoveSliderToTarget", "slider", "UISlider" },
    [86] = { CPMGameClassMoveSliderToTarget, CPMGameFieldMoveSliderToTargetTouchingSlider, 0x30u, 1, CPMGameValueKindBool, 0, "MoveSliderToTarget", "touchingSlider", "bool" },
    [87] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUIBackground, 0x20u, 8, CPMGameValueKindObject, 0, "JoystickNGUI", "background", "Transform" },
    [88] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUICenter, 0x28u, 8, CPMGameValueKindObject, 0, "JoystickNGUI", "center", "Transform" },
    [89] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUIRadius, 0x30u, 4, CPMGameValueKindFloat, 0, "JoystickNGUI", "radius", "float" },
    [90] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUIIsFloating, 0x34u, 1, CPMGameValueKindBool, 0, "JoystickNGUI", "isFloating", "bool" },
    [91] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUIConstraint, 0x38u, 4, CPMGameValueKindInt32, 0, "JoystickNGUI", "constraint", "Constraints" },
    [92] = { CPMGameClassJoystickNGUI, CPMGameFieldJoystickNGUIIsDrag, 0x9Cu, 1, CPMGameValueKindBool, 0, "JoystickNGUI", "isDrag", "bool" },
    [93] = { CPMGameClassUISlider, CPMGameFieldUISliderForeground, 0x80u, 8, CPMGameValueKindObject, 0, "UISlider", "foreground", "Transform" },
    [94] = { CPMGameClassUISlider, CPMGameFieldUISliderRawValue, 0x88u, 4, CPMGameValueKindFloat, 0, "UISlider", "rawValue", "float" },
    [95] = { CPMGameClassUISlider, CPMGameFieldUISliderDirection, 0x8Cu, 4, CPMGameValueKindInt32, 0, "UISlider", "direction", "Direction" },
    [96] = { CPMGameClassUIInput, CPMGameFieldUIInputLabel, 0x20u, 8, CPMGameValueKindObject, 0, "UIInput", "label", "UILabel" },
    [97] = { CPMGameClassUIInput, CPMGameFieldUIInputInputType, 0x28u, 4, CPMGameValueKindInt32, 0, "UIInput", "inputType", "InputType" },
    [98] = { CPMGameClassUIInput, CPMGameFieldUIInputValidation, 0x38u, 4, CPMGameValueKindInt32, 0, "UIInput", "validation", "Validation" },
    [99] = { CPMGameClassUIInput, CPMGameFieldUIInputCharacterLimit, 0x3Cu, 4, CPMGameValueKindInt32, 0, "UIInput", "characterLimit", "int" },
    [100] = { CPMGameClassUIInput, CPMGameFieldUIInputOnSubmit, 0x80u, 8, CPMGameValueKindObject, 0, "UIInput", "onSubmit", "List<EventDelegate>" },
    [101] = { CPMGameClassUIInput, CPMGameFieldUIInputOnChange, 0x88u, 8, CPMGameValueKindObject, 0, "UIInput", "onChange", "List<EventDelegate>" },
    [102] = { CPMGameClassUIInput, CPMGameFieldUIInputMValue, 0x98u, 8, CPMGameValueKindString, 0, "UIInput", "mValue", "string" },
    [103] = { CPMGameClassVinylData, CPMGameFieldVinylDataPosition, 0x10u, 12, CPMGameValueKindVector3, 0, "VinylData", "position", "Vector3" },
    [104] = { CPMGameClassVinylData, CPMGameFieldVinylDataScaleRotation, 0x1Cu, 12, CPMGameValueKindVector3, 0, "VinylData", "scaleRotation", "Vector3" },
    [105] = { CPMGameClassVinylData, CPMGameFieldVinylDataIconPosition, 0x28u, 12, CPMGameValueKindVector3, 0, "VinylData", "iconPosition", "Vector3" },
    [106] = { CPMGameClassVinylData, CPMGameFieldVinylDataText, 0x38u, 8, CPMGameValueKindString, 0, "VinylData", "text", "string" },
    [107] = { CPMGameClassVinylData, CPMGameFieldVinylDataColor, 0x40u, 4, CPMGameValueKindInt32, 0, "VinylData", "color", "uint" },
    [108] = { CPMGameClassVinylData, CPMGameFieldVinylDataPackedData, 0x48u, 8, CPMGameValueKindInt64, 0, "VinylData", "packedData", "long" },
    [109] = { CPMGameClassOneVynil, CPMGameFieldOneVynilVectors, 0x10u, 8, CPMGameValueKindObject, 0, "OneVynil", "vectors", "List<Vector3>" },
    [110] = { CPMGameClassOneVynil, CPMGameFieldOneVynilV, 0x18u, 8, CPMGameValueKindObject, 0, "OneVynil", "v", "List<string>" },
    [111] = { CPMGameClassOneVynil, CPMGameFieldOneVynilFloats, 0x20u, 8, CPMGameValueKindObject, 0, "OneVynil", "floats", "List<float>" },
    [112] = { CPMGameClassOneVynil, CPMGameFieldOneVynilText, 0x28u, 8, CPMGameValueKindString, 0, "OneVynil", "text", "string" },
    [113] = { CPMGameClassUnityObject, CPMGameFieldUnityObjectM_CachedPtr, 0x10u, 8, CPMGameValueKindInt64, 0, "Object", "m_CachedPtr", "IntPtr" },
    [114] = { CPMGameClassList1, CPMGameFieldList1Items, CPMGameOffsetRuntimeOnly, 8, CPMGameValueKindObject, 0, "List`1", "_items", "T[]" },
    [115] = { CPMGameClassList1, CPMGameFieldList1Size, CPMGameOffsetRuntimeOnly, 4, CPMGameValueKindInt32, 0, "List`1", "_size", "int" },
    [116] = { CPMGameClassList1, CPMGameFieldList1Version, CPMGameOffsetRuntimeOnly, 4, CPMGameValueKindInt32, 0, "List`1", "_version", "int" },
    [117] = { CPMGameClassDictionary2, CPMGameFieldDictionary2Buckets, CPMGameOffsetRuntimeOnly, 8, CPMGameValueKindObject, 0, "Dictionary`2", "_buckets", "int[]" },
    [118] = { CPMGameClassDictionary2, CPMGameFieldDictionary2Count, CPMGameOffsetRuntimeOnly, 4, CPMGameValueKindInt32, 0, "Dictionary`2", "_count", "int" },
    [119] = { CPMGameClassDictionary2, CPMGameFieldDictionary2Entries, CPMGameOffsetRuntimeOnly, 8, CPMGameValueKindObject, 0, "Dictionary`2", "_entries", "Dictionary<T0, T1>[]" },
};

NSInteger CPMGameLayoutClassCount(void) {
    return 16;
}

NSInteger CPMGameLayoutFieldCount(void) {
    return 120;
}

uint32_t CPMGameLayoutOffset(CPMGameClassID cls, CPMGameFieldID field) {
    if (field < 0 || field >= CPMGameFieldCount) return CPMGameOffsetNone;
    const CPMGameFieldRecord *rec = &CPMGameFieldTable[field];
    if (rec->cls != cls) return CPMGameOffsetNone;
    return rec->offset;
}

const char *_Nullable CPMGameLayoutClassName(CPMGameClassID cls) {
    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;
    return CPMGameClassTable[cls].className;
}

const char *_Nullable CPMGameLayoutClassNamespace(CPMGameClassID cls) {
    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;
    return CPMGameClassTable[cls].namesp;
}

const char *_Nullable CPMGameLayoutClassAssembly(CPMGameClassID cls) {
    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;
    return CPMGameClassTable[cls].assembly;
}

const char *_Nullable CPMGameLayoutFieldName(CPMGameFieldID field) {
    if (field < 0 || field >= CPMGameFieldCount) return NULL;
    return CPMGameFieldTable[field].fieldName;
}

CPMGameClassID CPMGameLayoutClassForName(NSString *className) {
    if (className.length == 0) return CPMGameClassNone;
    for (CPMGameClassID i = 0; i < CPMGameLayoutClassCount(); i++) {
        if ([className isEqualToString:@(CPMGameClassTable[i].className)]) return i;
    }
    return CPMGameClassNone;
}

CPMGameFieldID CPMGameLayoutFieldForName(CPMGameClassID cls, NSString *fieldName) {
    if (fieldName.length == 0) return CPMGameFieldNone;
    for (CPMGameFieldID i = 0; i < CPMGameFieldCount; i++) {
        if (CPMGameFieldTable[i].cls != cls) continue;
        if ([fieldName isEqualToString:@(CPMGameFieldTable[i].fieldName)]) return i;
    }
    return CPMGameFieldNone;
}

BOOL CPMGameLayoutIsSelfContained(void) {
    return CPMGameLayoutRuntimeOnlyFieldCount() == 0;
}

NSInteger CPMGameLayoutRuntimeOnlyFieldCount(void) {
    static NSInteger cached = -1;
    if (cached >= 0) return cached;
    NSInteger n = 0;
    for (CPMGameFieldID i = 0; i < CPMGameFieldCount; i++) {
        if (CPMGameFieldTable[i].offset == CPMGameOffsetRuntimeOnly) n++;
    }
    cached = n;
    return n;
}

NSString *CPMGameLayoutSignature(void) {
    return [NSString stringWithFormat:@"dump %@ / %ld types / %ld fields (%ld runtime-only)",
            CPM_GAME_LAYOUT_DUMP_SHA256, (long)21013, (long)CPMGameLayoutFieldCount(),
            (long)CPMGameLayoutRuntimeOnlyFieldCount()];
}
