/**
 * CPMGameLayout.h -- generated by tools/cpm_il2cpp.py - DO NOT EDIT.
 *
 * Field offsets, enum values and type names taken from the game's IL2CPP dump
 * (dump.cs, sha256 75d42adc05b0248a, 25357907 bytes,
 *  170 images / 21013 types).
 *
 * Do not hand-edit: run `make layout` after re-dumping the game.
 */
#ifndef CPMGameLayout_h
#define CPMGameLayout_h

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

#define CPM_GAME_LAYOUT_DUMP_SHA256 @"75d42adc05b0248aa537335f10555dc3789a9a449f748150ff92fdf002b2ac86"
#define CPM_GAME_LAYOUT_DUMP_BYTES 25357907
#define CPM_GAME_LAYOUT_TYPE_COUNT 21013
#define CPM_GAME_LAYOUT_IMAGE_COUNT 170
#define CPM_GAME_LAYOUT_STICKER_ITEM_SIZE 0

/// Offset the dump could not know (generic definition laid out at runtime).
static const uint32_t CPMGameOffsetRuntimeOnly = 0xFFFFFFFFu;
static const uint32_t CPMGameOffsetNone = 0xFFFFFFFEu;

typedef NS_ENUM(NSInteger, CPMGameClassID) {
    CPMGameClassNone = -1,
    CPMGameClassVinylsEditor,
    CPMGameClassVinylDrawer,
    CPMGameClassVinylContainer,
    CPMGameClassVinylsEditorUI,
    CPMGameClassStickerItem,
    CPMGameClassSelectSticker,
    CPMGameClassMoveSliderToTarget,
    CPMGameClassJoystickNGUI,
    CPMGameClassUISlider,
    CPMGameClassUIInput,
    CPMGameClassVinylData,
    CPMGameClassOneVynil,
    CPMGameClassUnityObject,
    CPMGameClassGameObject,
    CPMGameClassList1,
    CPMGameClassDictionary2,
    CPMGameClassCount = 16,
};

typedef NS_ENUM(NSInteger, CPMGameFieldID) {
    CPMGameFieldNone = -1,
    CPMGameFieldVinylsEditorSideCheckParent = 0,
    CPMGameFieldVinylsEditorScaleQuad = 1,
    CPMGameFieldVinylsEditorZoomSlider = 2,
    CPMGameFieldVinylsEditorRotationSlider = 3,
    CPMGameFieldVinylsEditorScaleSliderX = 4,
    CPMGameFieldVinylsEditorScaleSliderY = 5,
    CPMGameFieldVinylsEditorScaleSlider = 6,
    CPMGameFieldVinylsEditorJoystickSlider = 7,
    CPMGameFieldVinylsEditorJoystickUI = 8,
    CPMGameFieldVinylsEditorStickersScrollBar = 9,
    CPMGameFieldVinylsEditorStickersScrollView = 10,
    CPMGameFieldVinylsEditorVinylsCountLabel = 11,
    CPMGameFieldVinylsEditorEditUI = 12,
    CPMGameFieldVinylsEditorStickersWidget = 13,
    CPMGameFieldVinylsEditorVinylTransformEditPanel = 14,
    CPMGameFieldVinylsEditorAngleInputField = 15,
    CPMGameFieldVinylsEditorScaleXInputField = 16,
    CPMGameFieldVinylsEditorScaleYInputField = 17,
    CPMGameFieldVinylsEditorAngleText = 18,
    CPMGameFieldVinylsEditorScaleXText = 19,
    CPMGameFieldVinylsEditorScaleYText = 20,
    CPMGameFieldVinylsEditorEditorUI = 21,
    CPMGameFieldVinylsEditorCurrentVinyl = 22,
    CPMGameFieldVinylsEditorCurrentVinylsType = 23,
    CPMGameFieldVinylsEditorCurrentOperation = 24,
    CPMGameFieldVinylsEditorCurrentStickersParent = 25,
    CPMGameFieldVinylsEditorCurrentSticker = 26,
    CPMGameFieldVinylsEditorCurrentPivotTransform = 27,
    CPMGameFieldVinylsEditorLastVinylOrder = 28,
    CPMGameFieldVinylsEditorIsEditingExisting = 29,
    CPMGameFieldVinylsEditorIsMerged = 30,
    CPMGameFieldVinylsEditorSaved = 31,
    CPMGameFieldVinylsEditorAllStickers = 32,
    CPMGameFieldVinylsEditorEditingStickers = 33,
    CPMGameFieldVinylsEditorGroupParent = 34,
    CPMGameFieldVinylsEditorIsDragging = 35,
    CPMGameFieldVinylsEditorRenderDirty = 36,
    CPMGameFieldVinylsEditorVinylsTypeId = 37,
    CPMGameFieldVinylsEditorMaxVinylsCount = 38,
    CPMGameFieldVinylsEditorHasVinyl = 39,
    CPMGameFieldVinylDrawerCamera = 40,
    CPMGameFieldVinylDrawerVinylPrefab = 41,
    CPMGameFieldVinylDrawerVinylPrefabFonts = 42,
    CPMGameFieldVinylDrawerContainer = 43,
    CPMGameFieldVinylDrawerPlaneMaterial = 44,
    CPMGameFieldVinylDrawerFactory = 45,
    CPMGameFieldVinylDrawerInstance = 46,
    CPMGameFieldVinylContainerVinylsHolders = 47,
    CPMGameFieldVinylsEditorUIEditPlane = 48,
    CPMGameFieldVinylsEditorUIVisualIcons = 49,
    CPMGameFieldVinylsEditorUIPosCollider = 50,
    CPMGameFieldVinylsEditorUIRotCollider = 51,
    CPMGameFieldVinylsEditorUIScaleCollider = 52,
    CPMGameFieldVinylsEditorUIPosIcon = 53,
    CPMGameFieldVinylsEditorUIRotIcon = 54,
    CPMGameFieldVinylsEditorUIScaleIcon = 55,
    CPMGameFieldVinylsEditorUIMiddlePoint = 56,
    CPMGameFieldStickerItemTexture = 57,
    CPMGameFieldStickerItemSprite = 58,
    CPMGameFieldStickerItemOrder = 59,
    CPMGameFieldStickerItemStckerIndex = 60,
    CPMGameFieldStickerItemPosition = 61,
    CPMGameFieldStickerItemPositionIcon = 62,
    CPMGameFieldStickerItemEuler = 63,
    CPMGameFieldStickerItemScale = 64,
    CPMGameFieldStickerItemColor = 65,
    CPMGameFieldStickerItemThisVinyl = 66,
    CPMGameFieldStickerItemYAngle = 67,
    CPMGameFieldStickerItemXAngle = 68,
    CPMGameFieldStickerItemFlipX = 69,
    CPMGameFieldStickerItemInitialColorBackround = 70,
    CPMGameFieldStickerItemIsText = 71,
    CPMGameFieldStickerItemText = 72,
    CPMGameFieldStickerItemFontIndex = 73,
    CPMGameFieldStickerItemItalic = 74,
    CPMGameFieldStickerItemBold = 75,
    CPMGameFieldStickerItemOldIndex = 76,
    CPMGameFieldSelectStickerIdText = 77,
    CPMGameFieldSelectStickerGeneralControl = 78,
    CPMGameFieldSelectStickerVinylsEditor = 79,
    CPMGameFieldSelectStickerStickerSelected = 80,
    CPMGameFieldSelectStickerStickerIndex = 81,
    CPMGameFieldSelectStickerSelectWheelCts = 82,
    CPMGameFieldMoveSliderToTargetTarget = 83,
    CPMGameFieldMoveSliderToTargetSpeed = 84,
    CPMGameFieldMoveSliderToTargetSlider = 85,
    CPMGameFieldMoveSliderToTargetTouchingSlider = 86,
    CPMGameFieldJoystickNGUIBackground = 87,
    CPMGameFieldJoystickNGUICenter = 88,
    CPMGameFieldJoystickNGUIRadius = 89,
    CPMGameFieldJoystickNGUIIsFloating = 90,
    CPMGameFieldJoystickNGUIConstraint = 91,
    CPMGameFieldJoystickNGUIIsDrag = 92,
    CPMGameFieldUISliderForeground = 93,
    CPMGameFieldUISliderRawValue = 94,
    CPMGameFieldUISliderDirection = 95,
    CPMGameFieldUIInputLabel = 96,
    CPMGameFieldUIInputInputType = 97,
    CPMGameFieldUIInputValidation = 98,
    CPMGameFieldUIInputCharacterLimit = 99,
    CPMGameFieldUIInputOnSubmit = 100,
    CPMGameFieldUIInputOnChange = 101,
    CPMGameFieldUIInputMValue = 102,
    CPMGameFieldVinylDataPosition = 103,
    CPMGameFieldVinylDataScaleRotation = 104,
    CPMGameFieldVinylDataIconPosition = 105,
    CPMGameFieldVinylDataText = 106,
    CPMGameFieldVinylDataColor = 107,
    CPMGameFieldVinylDataPackedData = 108,
    CPMGameFieldOneVynilVectors = 109,
    CPMGameFieldOneVynilV = 110,
    CPMGameFieldOneVynilFloats = 111,
    CPMGameFieldOneVynilText = 112,
    CPMGameFieldUnityObjectM_CachedPtr = 113,
    CPMGameFieldList1Items = 114,
    CPMGameFieldList1Size = 115,
    CPMGameFieldList1Version = 116,
    CPMGameFieldDictionary2Buckets = 117,
    CPMGameFieldDictionary2Count = 118,
    CPMGameFieldDictionary2Entries = 119,
    CPMGameFieldCount = 120,
};

/// CPM.Scripts.VinylDrawer.VinylsType (from the dump)
static const NSInteger CPMGameEVinylsTypeNone = 0;
static const NSInteger CPMGameEVinylsTypeCarVinyls = 1;
static const NSInteger CPMGameEVinylsTypePlateVinyls = 2;
static const NSInteger CPMGameEVinylsTypeClanVinyls = 3;
static const NSInteger CPMGameEVinylsTypeWindowVinyls = 4;

/// CPM.Scripts.VinylDrawer.VinylsEditorOperation (from the dump)
static const NSInteger CPMGameEVinylsEditorOperationNone = 0;
static const NSInteger CPMGameEVinylsEditorOperationCreate = 1;
static const NSInteger CPMGameEVinylsEditorOperationMove = 2;
static const NSInteger CPMGameEVinylsEditorOperationRotate = 3;
static const NSInteger CPMGameEVinylsEditorOperationScale = 4;

typedef struct {
    CPMGameClassID cls;
    CPMGameFieldID field;
    uint32_t offset;      /* dump offset, or CPMGameOffsetRuntimeOnly */
    uint16_t size;        /* 0 = unknown */
    uint8_t kind;         /* CPMGameValueKind */
    uint8_t isStatic;
    const char *className;
    const char *fieldName;
    const char *typeName;
} CPMGameFieldRecord;

typedef NS_ENUM(NSInteger, CPMGameValueKind) {
    CPMGameValueKindUnknown = 0,
    CPMGameValueKindBool = 1,
    CPMGameValueKindInt32 = 2,
    CPMGameValueKindInt64 = 3,
    CPMGameValueKindFloat = 4,
    CPMGameValueKindDouble = 5,
    CPMGameValueKindObject = 6,
    CPMGameValueKindString = 7,
    CPMGameValueKindVector2 = 8,
    CPMGameValueKindVector3 = 9,
    CPMGameValueKindVector4 = 10,
    CPMGameValueKindColor = 11,
    CPMGameValueKindUInt8 = 12,
};

extern const CPMGameFieldRecord CPMGameFieldTable[CPMGameFieldCount];

/// Number of entries in the generated tables.
NSInteger CPMGameLayoutClassCount(void);
NSInteger CPMGameLayoutFieldCount(void);

/// Dump-relative offset for a field; CPMGameOffsetRuntimeOnly when the dump
/// cannot know it (generic definitions) and CPMGameOffsetNone when absent.
uint32_t CPMGameLayoutOffset(CPMGameClassID cls, CPMGameFieldID field);

/// Name lookups (stable UTF-8, owned by the __TEXT segment).
const char *_Nullable CPMGameLayoutClassName(CPMGameClassID cls);
const char *_Nullable CPMGameLayoutClassNamespace(CPMGameClassID cls);
const char *_Nullable CPMGameLayoutClassAssembly(CPMGameClassID cls);
const char *_Nullable CPMGameLayoutFieldName(CPMGameFieldID field);
CPMGameClassID CPMGameLayoutClassForName(NSString *className);
CPMGameFieldID CPMGameLayoutFieldForName(CPMGameClassID cls, NSString *fieldName);

/// Human readable one-liner for logs / the settings panel: dump hash + coverage.
NSString *CPMGameLayoutSignature(void);

/// YES when every needed offset came from the dump (no runtime-only holes).
BOOL CPMGameLayoutIsSelfContained(void);
NSInteger CPMGameLayoutRuntimeOnlyFieldCount(void);

NS_ASSUME_NONNULL_END
#endif /* CPMGameLayout_h */
