#!/usr/bin/env python3
"""Turn the game's IL2CPP `dump.cs` into the layout tables this tweak ships with.

    python3 tools/cpm_il2cpp.py generate     # regenerate the derived files
    python3 tools/cpm_il2cpp.py check        # fail if the committed files drifted from dump.cs
    python3 tools/cpm_il2cpp.py show         # print the extracted manifest as JSON
    python3 tools/cpm_il2cpp.py selftest     # assert known facts about the checked-in dump

Why this exists
---------------
Car Parking Multiplayer is a Unity IL2CPP build.  Everything the automation needs
(which class holds the vinyl editor, where the sticker list lives inside it, what the
`VinylsType` values are, how big a `StickerItem` layer record is) is *not* guessable -
it moves with every game update.  Il2CppDumper's `dump.cs` has all of it, but reading a
730k-line text file at runtime is not an option, so this tool extracts the subset named
in `tools/cpm_layout_spec.json` and emits:

    Resources/cpm_il2cpp_layout.json   machine readable, bundled with the dylib
    Core/CPMGameLayout.h               offsets + enums the Objective-C code compiles against
    Core/CPMGameLayout.m               lookup tables + staleness reporting

Fields whose offset the dump cannot know (generic type definitions such as List`1 are
emitted with 0x0 by Il2CppDumper) are marked "runtimeOnly"; CPMGameLayout.h gives them
CPMGameOffsetRuntimeOnly and the bridge resolves them from the live binary instead.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "tools" / "cpm_layout_spec.json"
GENERATED_MARK = "generated by tools/cpm_il2cpp.py - DO NOT EDIT"

IMAGE_RE = re.compile(r"^// Image (\d+): (.+?) - \d+\s*$")
NS_RE = re.compile(r"^// Namespace: (?:(?P<ns>.*?) - )?(?P<asm>\S+)\s*$")
IMG_LINE_RE = re.compile(r"^// Image: (?P<asm>\S+)\s*$")
TYPE_RE = re.compile(
    r"^(?P<mods>(?:(?:public|private|protected|internal|abstract|sealed|static|readonly|beforefieldinit)\s+)*)"
    r"(?P<kind>class|struct|enum|interface)\s+(?P<name>[^\s:{]+)"
    r"(?:\s*:\s*(?P<base>[^{]+?))?\s*(?://\s*TypeDefIndex:\s*(?P<tdi>\d+))?\s*$"
)
FIELD_RE = re.compile(
    r"^\s*(?P<mods>(?:(?:public|private|protected|internal|static|readonly|const|volatile)\s+)*)"
    r"(?P<type>[^;=]+?)\s+(?P<name><\w+>k__BackingField|\w+)\s*"
    r"(?:=\s*(?P<cval>[^;]+?))?\s*;\s*(?://\s*(?P<off>0x[0-9A-Fa-f]+))?\s*$"
)
METHOD_RE = re.compile(
    r"^\s*(?P<mods>(?:(?:public|private|protected|internal|static|virtual|override|abstract|sealed|extern|hidebysig|new)\s+)*)"
    r"(?P<ret>[^(]+?)\s+(?P<name>\.ctor|\.cctor|<[^>]+>b__\w+|\w+(?:\.\w+)*)\s*"
    r"\((?P<params>[^)]*)\)\s*(?:where [^{]*)?\{\s*\}\s*$"
)
RVA_RE = re.compile(r"^// RVA: (?P<rva>0x[0-9A-F]+)\s+Offset: (?P<off>0x[0-9A-F]+)\s+VA: (?P<va>0x[0-9A-F]+)")
ENUM_MEMBER_RE = re.compile(r"^\s*(?P<name>\w+)\s*=\s*(?P<value>-?0x[0-9A-Fa-f]+|-?\d+)u?[,;]?\s*$")
SECTION_RE = re.compile(r"^//\s*(Fields|Properties|Methods|Constructors)\s*$")

TYPE_KINDS = [
    (r"^bool$", ("bool", 1)),
    (r"^byte$|^System\.Byte$", ("u8", 1)),
    (r"^sbyte$|^System\.SByte$", ("i8", 1)),
    (r"^char$|^System\.Char$", ("char", 2)),
    (r"^short$|^System\.Int16$", ("i16", 2)),
    (r"^ushort$|^System\.UInt16$", ("u16", 2)),
    (r"^int$|^System\.Int32$|^System\.UInt32$|^uint$", ("i32", 4)),
    (r"^long$|^System\.Int64$|^ulong$|^System\.UInt64$|^IntPtr$|^System\.UIntPtr$", ("i64", 8)),
    (r"^float$|^System\.Single$", ("f32", 4)),
    (r"^double$|^System\.Double$", ("f64", 8)),
    (r"Vector2$|^UnityEngine\.Vector2$", ("vec2", 8)),
    (r"Vector3$|^UnityEngine\.Vector3$", ("vec3", 12)),
    (r"Vector4$|^UnityEngine\.Vector4$|^Quaternion$", ("vec4", 16)),
    (r"Color$|^UnityEngine\.Color32$", ("color", 16)),
    (r"Color32$", ("color", 4)),
    (r"Bounds$|^UnityEngine\.Bounds", ("bounds", 24)),
    (r"^\s*(public |private |internal )*string\b", ("string", 8)),
]


def classify(typ: str) -> tuple[str, int]:
    """Map a dump type name onto (kind, size) as the runtime reader needs it."""
    t = typ.strip()
    t = re.sub(r"\s*\{\s*get.*$", "", t)
    for pat, out in TYPE_KINDS:
        if re.search(pat, t):
            return out
    if t.endswith("*") or t.endswith("[]"):
        return ("ptr", 8)
    if re.match(r"^[A-Z]", t) and "." in t or t[:1].isupper():
        # anything that looks like a managed reference (class/interface/array/Nullable<>)
        if "<" in t and not t.startswith("System.Nullable"):
            return ("object", 8)
        return ("object", 8)
    return ("unknown", 0)


def clean_type(t: str) -> str:
    t = t.strip()
    t = re.sub(r"\s+", " ", t)
    return t


class Dump:
    """Streaming parser for Il2CppDumper's dump.cs."""

    def __init__(self, path: Path):
        self.path = path
        self.images: list[str] = []
        self.types: dict[str, dict] = {}          # "ns.Name" -> record (first match wins)
        self.all_types: dict[str, list[dict]] = {}  # "ns.Name" -> every match (name collisions across images)
        self.enum_values: dict[str, dict[str, int]] = {}
        self.enum_size: dict[str, int] = {}   # bare + dotted name -> field size in bytes
        self.type_count = 0
        self.parse()

    # -- parsing ---------------------------------------------------------
    def parse(self) -> None:
        cur: dict | None = None
        section = ""
        ns, asm = "", ""
        pending_rva: dict | None = None
        in_body = False
        depth = 0

        with self.path.open("r", encoding="utf-8", errors="replace") as fh:
            for raw in fh:
                line = raw.rstrip("\n")

                m = IMAGE_RE.match(line)
                if m and not in_body:
                    self.images.append(m.group(2))
                    continue
                if line.startswith("// Namespace:") or line.startswith("// Image:"):
                    ns, asm = "", ""
                    mm = NS_RE.match(line)
                    if mm:
                        ns = (mm.group("ns") or "").strip()
                        asm = mm.group("asm").strip()
                        continue
                    mm = IMG_LINE_RE.match(line)
                    if mm:
                        asm = mm.group("asm").strip()
                        ns = ""
                        continue
                    continue

                if not in_body:
                    mt = TYPE_RE.match(line)
                    if mt and mt.group("kind") in ("class", "struct", "enum", "interface"):
                        name = mt.group("name").strip()
                        kind = mt.group("kind")
                        full = f"{ns}.{name}" if ns else name
                        cur = {
                            "name": name,
                            "namespace": ns,
                            "assembly": asm,
                            "kind": kind,
                            "base": (mt.group("base") or "").strip().rstrip("{").strip(),
                            "typedefIndex": int(mt.group("tdi")) if mt.group("tdi") else None,
                            "fields": {},
                            "staticFields": {},
                            "methods": {},
                            "properties": {},
                            "enumValues": {},
                        }
                        section = ""
                        pending_rva = None
                        in_body = True
                        depth = 0
                    continue

                # inside a type body
                stripped = line.strip()
                if stripped == "{":
                    depth += 1
                    continue
                if stripped == "}":
                    depth -= 1
                    if depth <= 0:
                        assert cur is not None
                        self.add(cur)
                        cur = None
                        in_body = False
                    continue

                if cur is None:
                    continue

                ms = SECTION_RE.match(stripped)
                if ms:
                    section = ms.group(1)
                    continue
                mr = RVA_RE.match(stripped)
                if mr:
                    pending_rva = {k: int(v, 16) for k, v in mr.groupdict().items()}
                    continue

                if section in ("Fields", "Properties", ""):
                    mf = FIELD_RE.match(line)
                    if mf:
                        self.add_field(cur, mf)
                        continue
                if section in ("Methods", "Constructors", ""):
                    mmth = METHOD_RE.match(line)
                    if mmth:
                        self.add_method(cur, mmth, pending_rva)
                        pending_rva = None
                        continue
                if cur["kind"] == "enum":
                    me = ENUM_MEMBER_RE.match(line)
                    if me:
                        v = me.group("value")
                        cur["enumValues"][me.group("name")] = int(v, 0)
                        continue

    def add_field(self, cur: dict, mf: re.Match) -> None:
        mods = mf.group("mods") or ""
        typ = clean_type(mf.group("type"))
        name = mf.group("name")
        off_txt = mf.group("off")
        off = int(off_txt, 16) if off_txt else None
        is_static = "static" in mods
        is_const = "const" in mods
        if is_const:
            return
        kind, size = classify(typ)
        rec = {
            "type": typ,
            "offset": off,
            "size": size,
            "kind": kind,
            "static": is_static,
            "readonly": "readonly" in mods,
            "access": ("public" if "public" in mods else
                       "private" if "private" in mods else
                       "protected" if "protected" in mods else "internal"),
        }
        # Generic type *definitions* are dumped with 0x0 offsets: the real layout only
        # exists once the runtime instantiates List<T>/Dictionary<K,V>.
        if not is_static and (off is None or off == 0):
            rec["offset"] = None
            rec["runtimeOnly"] = True
        if is_static and "k__BackingField" in name:
            rec["runtimeOnly"] = False
        bucket = cur["staticFields"] if is_static else cur["fields"]
        bucket[name] = rec

    def add_method(self, cur: dict, mmth: re.Match, rva: dict | None) -> None:
        mods = mmth.group("mods") or ""
        name = mmth.group("name")
        params = clean_type(mmth.group("params") or "")
        params = re.sub(r"\s*,\s*", ", ", params)
        rec = {
            "return": clean_type(mmth.group("ret")),
            "params": params,
            "static": "static" in mods,
            "access": ("public" if "public" in mods else
                       "private" if "private" in mods else
                       "protected" if "protected" in mods else "internal"),
        }
        if rva:
            rec["rva"] = rva["rva"]
            rec["va"] = rva["va"]
        key = name
        if params:
            arity = len([p for p in params.split(",") if p.strip()])
            key = f"{name}/{arity}"
        cur["methods"][key] = rec
        cur["methods"].setdefault(name, rec)

    def add(self, cur: dict) -> None:
        self.type_count += 1
        if cur["kind"] == "enum":
            size = {"byte": 1, "sbyte": 1, "short": 2, "ushort": 2,
                    "uint": 4, "int": 4, "long": 8, "ulong": 8}.get(cur["base"], 4)
            full = f"{cur['namespace']}.{cur['name']}" if cur["namespace"] else cur["name"]
            for key in (full, cur["name"]):
                self.enum_size.setdefault(key, size)
        full = f"{cur['namespace']}.{cur['name']}" if cur["namespace"] else cur["name"]
        self.all_types.setdefault(full, []).append(cur)
        # First definition wins unless a later one carries an explicit namespace for a
        # name the spec asked for without one (e.g. global-namespace StickerItem).
        self.types.setdefault(full, cur)
        if cur["kind"] == "enum":
            self.enum_values.setdefault(full, cur["enumValues"])

    # -- lookups ---------------------------------------------------------
    def find(self, dotted: str) -> dict | None:
        """Look a type up by `namespace.Name` (or bare name).

        Unity/NGUI ship several assemblies that define the *same* dotted type name
        (UnityEngine.Object exists in UnityEngine.dll as a stub and in
        UnityEngine.CoreModule.dll with the real fields), so every match is merged:
        a field is taken from whichever definition actually declares it.
        """
        matches = self.find_all(dotted)
        if not matches:
            return None
        if len(matches) == 1:
            return matches[0]
        best = max(matches, key=lambda r: len(r["fields"]) + len(r["methods"]))
        merged = dict(best)
        for key in ("fields", "staticFields", "methods", "properties", "enumValues"):
            union: dict = {}
            for rec in matches:
                for name, val in rec.get(key, {}).items():
                    union.setdefault(name, val)
            merged[key] = union
        return merged

    def find_all(self, dotted: str) -> list[dict]:
        bare = dotted.split(".")[-1]
        out = []
        for key, lst in self.all_types.items():
            if key == dotted or key.split(".")[-1] == bare:
                out.extend(lst)
        return out


def select(names: list[str], available: dict) -> tuple[dict, list[str], list[str]]:
    """Apply a spec selector list to a {name: rec} mapping."""
    wanted: dict = {}
    missing: list[str] = []
    if names == ["*"]:
        return dict(available), [], []
    excludes = {n[1:] for n in names if n.startswith("!")}
    for want in names:
        if want.startswith("!"):
            continue
        if want in available and want not in excludes:
            wanted[want] = available[want]
        else:
            missing.append(want)
    return wanted, missing, sorted(excludes)


def build_manifest(dump: Dump, spec: dict) -> tuple[dict, list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    classes: dict[str, dict] = {}

    for want in spec.get("classes", []):
        optional = bool(want.get("optional"))
        dotted = want["name"]
        if want.get("namespace") == "" and "." in dotted:
            dotted = dotted.split(".")[-1]
        rec = dump.find(dotted)
        if rec is None:
            msg = f"class not found in dump.cs: {dotted}"
            (warnings if optional else errors).append(msg)
            continue
        every_field = dict(rec["fields"])
        every_field.update(rec["staticFields"])
        selected, miss_f, _ = select(want.get("fields", []), every_field)
        fields = {k: v for k, v in selected.items() if k in rec["fields"]}
        statics = {k: v for k, v in selected.items() if k in rec["staticFields"]}
        methods, miss_m, _ = select(want.get("methods", []), rec["methods"])
        missed = sorted(set(miss_f))
        if missed and want.get("fields") != ["*"]:
            msg = f"{dotted}: fields not in dump: {', '.join(missed)}"
            (warnings if optional else errors).append(msg)
        miss_m = [m for m in miss_m if "/" not in m]
        if miss_m and want.get("methods") != ["*"]:
            msg = f"{dotted}: methods not in dump: {', '.join(sorted(miss_m))}"
            (warnings if optional else errors).append(msg)

        def fix_enum(fdata: dict) -> dict:
            bare = re.sub(r"<.*$", "", (fdata.get("type") or "")).strip().split(".")[-1]
            size = dump.enum_size.get(bare)
            if size and fdata.get("kind") in ("object", "unknown"):
                fdata = dict(fdata)
                fdata["kind"] = "u8" if size == 1 else ("u16" if size == 2 else "i32")
                fdata["size"] = size
                fdata["enum"] = True
            return fdata

        fields = {k: fix_enum(v) for k, v in fields.items()}
        statics = {k: fix_enum(v) for k, v in statics.items()}
        classes[want["id"]] = {
            "className": rec["name"],
            "namespace": rec["namespace"],
            "assembly": rec["assembly"],
            "base": rec["base"],
            "typedefIndex": rec["typedefIndex"],
            "comment": want.get("comment", ""),
            "fields": {k: {kk: vv for kk, vv in v.items() if vv is not None} for k, v in fields.items()},
            "staticFields": {k: {kk: vv for kk, vv in v.items() if vv is not None} for k, v in statics.items()},
            "methods": {k: {kk: vv for kk, vv in v.items() if vv is not None}
                        for k, v in methods.items() if "/" not in k},
        }

    enums: dict[str, dict] = {}
    for want in spec.get("enums", []):
        dotted = want["name"]
        vals = dump.enum_values.get(dotted)
        if vals is None:
            rec = dump.find(dotted)
            vals = rec["enumValues"] if rec else None
        if not vals:
            msg = f"enum not found in dump.cs: {dotted}"
            (warnings if want.get("optional") else errors).append(msg)
            continue
        enums[want["id"]] = {
            "enumName": dotted.split(".")[-1],
            "namespace": dotted.rsplit(".", 1)[0] if "." in dotted else "",
            "values": vals,
        }

    return {"classes": classes, "enums": enums}, errors, warnings


def dump_identity(path: Path) -> dict:
    h = hashlib.sha256()
    size = 0
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
            size += len(chunk)
    return {"path": path.name, "bytes": size, "sha256": h.hexdigest(), "short": h.hexdigest()[:16]}


# --------------------------------------------------------------------------
# emitters
# --------------------------------------------------------------------------
def c_ident(*parts: str) -> str:
    out = ""
    for p in parts:
        # compiler-generated names: <Foo>k__BackingField -> Foo
        p = re.sub(r"^<(\w+)>k__BackingField$", r"\1", p)
        p = re.sub(r"[^0-9A-Za-z]+", "_", p).strip("_")
        if p:
            out += p[0].upper() + p[1:]
    return out


def emit_header(manifest: dict, ident: dict, meta: dict) -> str:
    L: list[str] = []
    a = L.append
    a("/**")
    a(f" * CPMGameLayout.h -- {GENERATED_MARK}.")
    a(" *")
    a(" * Field offsets, enum values and type names taken from the game's IL2CPP dump")
    a(f" * ({ident['path']}, sha256 {ident['short']}, {ident['bytes']} bytes,")
    a(f" *  {meta['images']} images / {meta['types']} types).")
    a(" *")
    a(" * Do not hand-edit: run `make layout` after re-dumping the game.")
    a(" */")
    a("#ifndef CPMGameLayout_h")
    a("#define CPMGameLayout_h")
    a("")
    a("#import <Foundation/Foundation.h>")
    a("")
    a("NS_ASSUME_NONNULL_BEGIN")
    a("")
    a(f"#define CPM_GAME_LAYOUT_DUMP_SHA256 @\"{ident['sha256']}\"")
    a(f"#define CPM_GAME_LAYOUT_DUMP_BYTES {ident['bytes']}")
    a(f"#define CPM_GAME_LAYOUT_TYPE_COUNT {meta['types']}")
    a(f"#define CPM_GAME_LAYOUT_IMAGE_COUNT {meta['images']}")
    a("#define CPM_GAME_LAYOUT_STICKER_ITEM_SIZE 0")
    a("")
    a("/// Offset the dump could not know (generic definition laid out at runtime).")
    a("static const uint32_t CPMGameOffsetRuntimeOnly = 0xFFFFFFFFu;")
    a("static const uint32_t CPMGameOffsetNone = 0xFFFFFFFEu;")
    a("")
    # class ids
    a("typedef NS_ENUM(NSInteger, CPMGameClassID) {")
    a("    CPMGameClassNone = -1,")
    for cid, rec in manifest["classes"].items():
        a(f"    CPMGameClass{c_ident(cid)},")
    a(f"    CPMGameClassCount = {len(manifest['classes'])},")
    a("};")
    a("")
    # field ids
    a("typedef NS_ENUM(NSInteger, CPMGameFieldID) {")
    a("    CPMGameFieldNone = -1,")
    fid = 0
    field_rows: list[tuple[int, int, str, str, str, bool, str, int]] = []
    for ci, (cid, rec) in enumerate(manifest["classes"].items()):
        for fname, fre in sorted(rec["fields"].items(), key=lambda kv: (kv[1].get("offset") is None, kv[1].get("offset") or 0, kv[0])):
            a(f"    CPMGameField{c_ident(cid, fname)} = {fid},")
            field_rows.append((ci, fid, cid, fname, fre.get("type", ""), False, fre.get("kind", "unknown"), int(fre.get("size", 0) or 0)))
            fid += 1
        for fname, fre in sorted(rec["staticFields"].items()):
            a(f"    CPMGameField{c_ident(cid, fname)} = {fid},")
            field_rows.append((ci, fid, cid, fname, fre.get("type", ""), True, fre.get("kind", "unknown"), int(fre.get("size", 0) or 0)))
            fid += 1
    a(f"    CPMGameFieldCount = {fid},")
    a("};")
    a("")
    # enums from the game
    for eid, erec in manifest["enums"].items():
        a(f"/// {erec['namespace']}.{erec['enumName']} (from the dump)")
        for name, value in sorted(erec["values"].items(), key=lambda kv: kv[1]):
            a(f"static const NSInteger CPMGameE{c_ident(eid, name)} = {value};")
        a("")
    a("typedef struct {")
    a("    CPMGameClassID cls;")
    a("    CPMGameFieldID field;")
    a("    uint32_t offset;      /* dump offset, or CPMGameOffsetRuntimeOnly */")
    a("    uint16_t size;        /* 0 = unknown */")
    a("    uint8_t kind;         /* CPMGameValueKind */")
    a("    uint8_t isStatic;")
    a("    const char *className;")
    a("    const char *fieldName;")
    a("    const char *typeName;")
    a("} CPMGameFieldRecord;")
    a("")
    a("typedef NS_ENUM(NSInteger, CPMGameValueKind) {")
    a("    CPMGameValueKindUnknown = 0,")
    a("    CPMGameValueKindBool = 1,")
    a("    CPMGameValueKindInt32 = 2,")
    a("    CPMGameValueKindInt64 = 3,")
    a("    CPMGameValueKindFloat = 4,")
    a("    CPMGameValueKindDouble = 5,")
    a("    CPMGameValueKindObject = 6,")
    a("    CPMGameValueKindString = 7,")
    a("    CPMGameValueKindVector2 = 8,")
    a("    CPMGameValueKindVector3 = 9,")
    a("    CPMGameValueKindVector4 = 10,")
    a("    CPMGameValueKindColor = 11,")
    a("    CPMGameValueKindUInt8 = 12,")
    a("};")
    a("")
    a("extern const CPMGameFieldRecord CPMGameFieldTable[CPMGameFieldCount];")
    a("")
    a("/// Number of entries in the generated tables.")
    a("NSInteger CPMGameLayoutClassCount(void);")
    a("NSInteger CPMGameLayoutFieldCount(void);")
    a("")
    a("/// Dump-relative offset for a field; CPMGameOffsetRuntimeOnly when the dump")
    a("/// cannot know it (generic definitions) and CPMGameOffsetNone when absent.")
    a("uint32_t CPMGameLayoutOffset(CPMGameClassID cls, CPMGameFieldID field);")
    a("")
    a("/// Name lookups (stable UTF-8, owned by the __TEXT segment).")
    a("const char *_Nullable CPMGameLayoutClassName(CPMGameClassID cls);")
    a("const char *_Nullable CPMGameLayoutClassNamespace(CPMGameClassID cls);")
    a("const char *_Nullable CPMGameLayoutClassAssembly(CPMGameClassID cls);")
    a("const char *_Nullable CPMGameLayoutFieldName(CPMGameFieldID field);")
    a("CPMGameClassID CPMGameLayoutClassForName(NSString *className);")
    a("CPMGameFieldID CPMGameLayoutFieldForName(CPMGameClassID cls, NSString *fieldName);")
    a("")
    a("/// Human readable one-liner for logs / the settings panel: dump hash + coverage.")
    a("NSString *CPMGameLayoutSignature(void);")
    a("")
    a("/// YES when every needed offset came from the dump (no runtime-only holes).")
    a("BOOL CPMGameLayoutIsSelfContained(void);")
    a("NSInteger CPMGameLayoutRuntimeOnlyFieldCount(void);")
    a("")
    a("NS_ASSUME_NONNULL_END")
    a("#endif /* CPMGameLayout_h */")
    return "\n".join(L) + "\n", field_rows


KIND_TO_ENUM = {
    "bool": "CPMGameValueKindBool",
    "i32": "CPMGameValueKindInt32",
    "i64": "CPMGameValueKindInt64",
    "f32": "CPMGameValueKindFloat",
    "f64": "CPMGameValueKindDouble",
    "object": "CPMGameValueKindObject",
    "ptr": "CPMGameValueKindObject",
    "string": "CPMGameValueKindString",
    "vec2": "CPMGameValueKindVector2",
    "vec3": "CPMGameValueKindVector3",
    "vec4": "CPMGameValueKindVector4",
    "color": "CPMGameValueKindColor",
    "u8": "CPMGameValueKindUInt8",
    "i8": "CPMGameValueKindUInt8",
    "u16": "CPMGameValueKindInt32",
    "i16": "CPMGameValueKindInt32",
    "char": "CPMGameValueKindUInt8",
    "bounds": "CPMGameValueKindUnknown",
}


def emit_impl(manifest: dict, ident: dict, meta: dict, field_rows) -> str:
    L: list[str] = []
    a = L.append
    a("/**")
    a(f" * CPMGameLayout.m -- {GENERATED_MARK}.")
    a(" *")
    a(f" * Source: {ident['path']} sha256={ident['short']} ({ident['bytes']} bytes).")
    a(" * Regenerate with: make layout")
    a(" */")
    a("#import \"CPMGameLayout.h\"")
    a("")
    a("#import <Foundation/Foundation.h>")
    a("")
    a("typedef struct {")
    a("    CPMGameClassID id;")
    a("    const char *className;")
    a("    const char *namesp;")
    a("    const char *assembly;")
    a("    NSInteger typedefIndex;")
    a("} CPMGameClassRecord;")
    a("")
    a(f"static const CPMGameClassRecord CPMGameClassTable[{len(manifest['classes'])}] = {{")
    for ci, (cid, rec) in enumerate(manifest["classes"].items()):
        tdi = rec["typedefIndex"] if rec["typedefIndex"] is not None else -1
        a(f"    [{ci}] = {{ CPMGameClass{c_ident(cid)}, \"{rec['className']}\", "
          f"\"{rec['namespace']}\", \"{rec['assembly']}\", {tdi} }},")
    a("};")
    a("")
    a(f"const CPMGameFieldRecord CPMGameFieldTable[CPMGameFieldCount] = {{")
    for ci, fi, cid, fname, ftype, is_static, kind, size in field_rows:
        rec = manifest["classes"][cid]
        for key, fdata in list(rec["fields"].items()) + list(rec["staticFields"].items()):
            if key == fname:
                off = fdata.get("offset")
                break
        else:
            off = None
        off_txt = f"0x{off:X}u" if isinstance(off, int) else "CPMGameOffsetRuntimeOnly"
        a(f"    [{fi}] = {{ CPMGameClass{c_ident(cid)}, CPMGameField{c_ident(cid, fname)}, "
          f"{off_txt}, {size}, {KIND_TO_ENUM.get(kind, 'CPMGameValueKindUnknown')}, {1 if is_static else 0}, "
          f"\"{rec['className']}\", \"{fname}\", \"{ftype}\" }},")
    a("};")
    a("")
    a("NSInteger CPMGameLayoutClassCount(void) {")
    a(f"    return {len(manifest['classes'])};")
    a("}")
    a("")
    a("NSInteger CPMGameLayoutFieldCount(void) {")
    a(f"    return {len(field_rows)};")
    a("}")
    a("")
    a("uint32_t CPMGameLayoutOffset(CPMGameClassID cls, CPMGameFieldID field) {")
    a("    if (field < 0 || field >= CPMGameFieldCount) return CPMGameOffsetNone;")
    a("    const CPMGameFieldRecord *rec = &CPMGameFieldTable[field];")
    a("    if (rec->cls != cls) return CPMGameOffsetNone;")
    a("    return rec->offset;")
    a("}")
    a("")
    a("const char *_Nullable CPMGameLayoutClassName(CPMGameClassID cls) {")
    a("    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;")
    a("    return CPMGameClassTable[cls].className;")
    a("}")
    a("")
    a("const char *_Nullable CPMGameLayoutClassNamespace(CPMGameClassID cls) {")
    a("    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;")
    a("    return CPMGameClassTable[cls].namesp;")
    a("}")
    a("")
    a("const char *_Nullable CPMGameLayoutClassAssembly(CPMGameClassID cls) {")
    a("    if (cls < 0 || (NSInteger)cls >= CPMGameLayoutClassCount()) return NULL;")
    a("    return CPMGameClassTable[cls].assembly;")
    a("}")
    a("")
    a("const char *_Nullable CPMGameLayoutFieldName(CPMGameFieldID field) {")
    a("    if (field < 0 || field >= CPMGameFieldCount) return NULL;")
    a("    return CPMGameFieldTable[field].fieldName;")
    a("}")
    a("")
    a("CPMGameClassID CPMGameLayoutClassForName(NSString *className) {")
    a("    if (className.length == 0) return CPMGameClassNone;")
    a("    for (CPMGameClassID i = 0; i < CPMGameLayoutClassCount(); i++) {")
    a("        if ([className isEqualToString:@(CPMGameClassTable[i].className)]) return i;")
    a("    }")
    a("    return CPMGameClassNone;")
    a("}")
    a("")
    a("CPMGameFieldID CPMGameLayoutFieldForName(CPMGameClassID cls, NSString *fieldName) {")
    a("    if (fieldName.length == 0) return CPMGameFieldNone;")
    a("    for (CPMGameFieldID i = 0; i < CPMGameFieldCount; i++) {")
    a("        if (CPMGameFieldTable[i].cls != cls) continue;")
    a("        if ([fieldName isEqualToString:@(CPMGameFieldTable[i].fieldName)]) return i;")
    a("    }")
    a("    return CPMGameFieldNone;")
    a("}")
    a("")
    a("BOOL CPMGameLayoutIsSelfContained(void) {")
    a(f"    return CPMGameLayoutRuntimeOnlyFieldCount() == 0;")
    a("}")
    a("")
    a("NSInteger CPMGameLayoutRuntimeOnlyFieldCount(void) {")
    a("    static NSInteger cached = -1;")
    a("    if (cached >= 0) return cached;")
    a("    NSInteger n = 0;")
    a("    for (CPMGameFieldID i = 0; i < CPMGameFieldCount; i++) {")
    a("        if (CPMGameFieldTable[i].offset == CPMGameOffsetRuntimeOnly) n++;")
    a("    }")
    a("    cached = n;")
    a("    return n;")
    a("}")
    a("")
    a("NSString *CPMGameLayoutSignature(void) {")
    a("    return [NSString stringWithFormat:@\"dump %@ / %ld types / %ld fields (%ld runtime-only)\",")
    a(f"            CPM_GAME_LAYOUT_DUMP_SHA256, (long){meta['types']}, (long)CPMGameLayoutFieldCount(),")
    a("            (long)CPMGameLayoutRuntimeOnlyFieldCount()];")
    a("}")
    return "\n".join(L) + "\n"


def emit_json(manifest: dict, ident: dict, meta: dict, errors: list[str]) -> str:
    out = {
        "_generated_by": GENERATED_MARK,
        "dump": ident,
        "images": meta["images"],
        "types": meta["types"],
        "classes": manifest["classes"],
        "enums": manifest["enums"],
    }
    return json.dumps(out, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def generate(dump_path: Path, spec_path: Path) -> tuple[dict, list[str], list[str], dict]:
    dump = Dump(dump_path)
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    manifest, errors, warnings = build_manifest(dump, spec)
    ident = dump_identity(dump_path)
    meta = {"images": len(dump.images), "types": dump.type_count}
    header, rows = emit_header(manifest, ident, meta)
    impl = emit_impl(manifest, ident, meta, rows)
    js = emit_json(manifest, ident, meta, errors)
    payload = {"manifest": manifest, "ident": ident, "meta": meta,
               "header": header, "impl": impl, "json": js,
               "errors": errors, "warnings": warnings}
    return payload


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("mode", choices=["generate", "check", "show", "selftest"])
    ap.add_argument("--dump", default=str(ROOT / "dump.cs"))
    ap.add_argument("--spec", default=str(SPEC_PATH))
    ap.add_argument("--out-json", default=str(ROOT / "Resources" / "cpm_il2cpp_layout.json"))
    ap.add_argument("--out-h", default=str(ROOT / "Core" / "CPMGameLayout.h"))
    ap.add_argument("--out-m", default=str(ROOT / "Core" / "CPMGameLayout.m"))
    args = ap.parse_args()

    dump_path = Path(args.dump)
    if not dump_path.exists():
        print(f"ERROR: dump.cs not found at {dump_path}", file=sys.stderr)
        return 2

    payload = generate(dump_path, Path(args.spec))
    errors, warnings = payload["errors"], payload["warnings"]

    if args.mode == "selftest":
        return selftest(dump_path, payload)

    if args.mode == "show":
        print(json.dumps(payload["manifest"], indent=2, sort_keys=True, ensure_ascii=False))
        for w in warnings:
            print("warn:", w, file=sys.stderr)
        return 1 if errors else 0

    targets = {
        Path(args.out_json): payload["json"],
        Path(args.out_h): payload["header"],
        Path(args.out_m): payload["impl"],
    }

    if args.mode == "check":
        bad = []
        for path, text in targets.items():
            if not path.exists():
                bad.append(f"{path.relative_to(ROOT)}: missing (run: make layout)")
            elif path.read_text(encoding="utf-8") != text:
                bad.append(f"{path.relative_to(ROOT)}: stale (run: make layout)")
        if errors:
            bad += [f"spec vs dump.cs: {e}" for e in errors]
        if bad:
            print("FAIL: generated IL2CPP layout out of date")
            for b in bad:
                print("  -", b)
            return 1
        print(f"OK: CPM layout matches dump.cs ({payload['meta']['types']} types, "
              f"{len(payload['manifest']['classes'])} classes)")
        for w in warnings:
            print("  note:", w)
        return 0

    for path, text in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
        else:
            print(f"unchanged {path.relative_to(ROOT)}")
    if errors:
        print("ERRORS (the game renamed something; update tools/cpm_layout_spec.json):")
        for e in errors:
            print("  -", e)
        return 1
    for w in warnings:
        print("warning:", w)
    fields = sum(len(c["fields"]) + len(c["staticFields"]) for c in payload["manifest"]["classes"].values())
    print(f"generated {len(payload['manifest']['classes'])} classes / {fields} fields / "
          f"{len(payload['manifest']['enums'])} enums")
    return 0


def selftest(dump_path: Path, payload: dict) -> int:
    """Facts the checked-in dump.cs must satisfy, so a re-dump is provably sane."""
    checks = [
        ("VinylsEditor exists", lambda m: "VinylsEditor" in m["classes"]),
        ("VinylsEditor._allStickers offset 0x258",
         lambda m: m["classes"]["VinylsEditor"]["fields"]["_allStickers"]["offset"] == 0x258),
        ("VinylsEditor._maxVinylsCount offset 0x2F8",
         lambda m: m["classes"]["VinylsEditor"]["fields"]["_maxVinylsCount"]["offset"] == 0x2F8),
        ("VinylsEditor._currentSticker offset 0x210",
         lambda m: m["classes"]["VinylsEditor"]["fields"]["_currentSticker"]["offset"] == 0x210),
        ("VinylDrawer._instance is static",
         lambda m: m["classes"]["VinylDrawer"]["staticFields"]["_instance"]["static"] is True),
        ("StickerItem.position offset 0x38",
         lambda m: m["classes"]["StickerItem"]["fields"]["position"]["offset"] == 0x38),
        ("StickerItem.scale is vec3",
         lambda m: m["classes"]["StickerItem"]["fields"]["scale"]["kind"] == "vec3"),
        ("VinylsType.CarVinyls == 1",
         lambda m: m["enums"]["VinylsType"]["values"]["CarVinyls"] == 1),
        ("VinylsType.WindowVinyls == 4",
         lambda m: m["enums"]["VinylsType"]["values"]["WindowVinyls"] == 4),
        ("VinylsEditorOperation.Scale == 4",
         lambda m: m["enums"]["VinylsEditorOperation"]["values"]["Scale"] == 4),
        ("VinylData.color is uint32 at 0x40",
         lambda m: m["classes"]["VinylData"]["fields"]["color"]["offset"] == 0x40
         and m["classes"]["VinylData"]["fields"]["color"]["kind"] == "i32"),
        ("List`1 offsets are runtime-only",
         lambda m: m["classes"]["List1"]["fields"]["_size"].get("runtimeOnly") is True),
        ("dump sha256 present", lambda p: len(p["ident"]["sha256"]) == 64),
    ]
    m = payload["manifest"]
    fails = []
    for name, fn in checks:
        try:
            ok = bool(fn(payload) if name == "dump sha256 present" else fn(m))
        except Exception as exc:  # noqa: BLE001
            ok = False
            name += f" ({exc})"
        print(("  ok   " if ok else "  FAIL ") + name)
        if not ok:
            fails.append(name)
    if payload["errors"]:
        for e in payload["errors"]:
            print("  FAIL spec error:", e)
        fails.append("spec errors")
    if fails:
        print(f"selftest FAILED ({len(fails)})")
        return 1
    print(f"selftest OK against {dump_path.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
