#!/usr/bin/env python3
"""
cpm_anchors.py — compile the UI anchor table into the binary.

Resources/cpm_ui_anchors.json describes where the vinyl editor's controls sit on a
reference device (points, y-down). The dylib is injected into the *game's* bundle, so
NSBundle.mainBundle can never find a JSON resource of ours — reading it at runtime
always failed. This script turns the table into a header that the linker puts in the
image, and `check` mode fails the build when the JSON and the header disagree.

    python3 tools/cpm_anchors.py generate   # rewrite Core/CPMAnchorsDefault.h
    python3 tools/cpm_anchors.py check      # staleness gate (exit 1 when out of date)
    python3 tools/cpm_anchors.py show       # print the parsed table
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "Resources" / "cpm_ui_anchors.json"
OUT_PATH = ROOT / "Core" / "CPMAnchorsDefault.h"

ELEMENT_TYPES = [
    "CPMUIElementTypeAddShape",
    "CPMUIElementTypeShapeSelector",
    "CPMUIElementTypeColorPicker",
    "CPMUIElementTypeRedSlider",
    "CPMUIElementTypeGreenSlider",
    "CPMUIElementTypeBlueSlider",
    "CPMUIElementTypeScaleSlider",
    "CPMUIElementTypeRotateSlider",
    "CPMUIElementTypeMoveJoystick",
    "CPMUIElementTypeConfirmButton",
    "CPMUIElementTypeCancelButton",
    "CPMUIElementTypeLayerListView",
    "CPMUIElementTypeZoomControl",
]

SLIDER_TYPES = {3, 4, 5, 6, 7}


def load() -> dict:
    data = json.loads(JSON_PATH.read_text())
    size = data.get("screenSize") or {}
    ref_w = float(size.get("width", 390))
    ref_h = float(size.get("height", 844))
    anchors = []
    for raw in data.get("anchors", []):
        t = int(raw.get("type", -1))
        if t < 0 or t >= len(ELEMENT_TYPES):
            raise SystemExit(f"anchor with unknown type {t}")
        c = raw.get("center") or {}
        s = raw.get("size") or {}
        anchors.append(
            {
                "type": t,
                "cx": float(c.get("x", 0)),
                "cy": float(c.get("y", 0)),
                "w": float(s.get("width", 0)),
                "h": float(s.get("height", 0)),
                "minX": float(raw.get("sliderMinX", 0)),
                "maxX": float(raw.get("sliderMaxX", 0)),
                "minY": float(raw.get("sliderMinY", 0)),
                "maxY": float(raw.get("sliderMaxY", 0)),
                "name": str(raw.get("displayName") or f"element{t}"),
                "valid": bool(raw.get("isValid", True)),
            }
        )
    seen = {a["type"] for a in anchors}
    missing = [ELEMENT_TYPES[i] for i in range(len(ELEMENT_TYPES)) if i not in seen]
    canvas = data.get("canvasRect") or {}
    return {
        "id": str(data.get("calibrationID") or "generated"),
        "canvas": canvas if canvas else None,
        "refW": ref_w,
        "refH": ref_h,
        "scale": float(data.get("scaleFactor", 1.0)),
        "landscape": bool(data.get("isLandscape", False)),
        "anchors": anchors,
        "missing": missing,
        "sha256": hashlib.sha256(JSON_PATH.read_bytes()).hexdigest(),
    }


def render(t: dict) -> str:
    lines = [
        "/**",
        " * CPMAnchorsDefault.h — GENERATED by tools/cpm_anchors.py. Do not edit.",
        " *",
        f" * source: Resources/cpm_ui_anchors.json  (sha256 {t['sha256']})",
        f" * calibration id: {t['id']}   reference screen: {t['refW']:g} x {t['refH']:g} pt"
        f"   landscape: {'yes' if t['landscape'] else 'no'}",
        " *",
        " * Coordinates are points on the *reference* device, origin top-left, y down.",
        " * CPMUICalibration scales them onto the real screen; the on-screen ROI editor",
        " * overrides them per device. Regenerate with: make anchors",
        " */",
        "#ifndef CPM_ANCHORS_DEFAULT_H",
        "#define CPM_ANCHORS_DEFAULT_H",
        "",
        "#import <CoreGraphics/CoreGraphics.h>",
        "#import <Foundation/Foundation.h>",
        "",
        "NS_ASSUME_NONNULL_BEGIN",
        "",
        '/* `type` mirrors CPMUIElementType (defined in CPMUICalibration.h) as a plain',
        ' * integer so this header stays includable in both directions. */',
        "",
        "typedef struct {",
        "    NSInteger type;",
        "    CGFloat centerX, centerY;      /* reference points */",
        "    CGFloat width, height;",
        "    CGFloat sliderMinX, sliderMaxX;  /* track ends, reference points */",
        "    CGFloat sliderMinY, sliderMaxY;",
        "    BOOL isSlider;",
        "    BOOL isValid;",
        "    const char *name;",
        "} CPMUIAnchorRecord;",
        "",
        f"#define CPM_ANCHOR_REFERENCE_WIDTH  {t['refW']}",
        f"#define CPM_ANCHOR_REFERENCE_HEIGHT {t['refH']}",
        f"#define CPM_ANCHOR_IS_LANDSCAPE     {1 if t['landscape'] else 0}",
        '#define CPM_ANCHOR_CALIBRATION_ID   @"' + t["id"].replace('"', '\\"') + '"',
        '#define CPM_ANCHOR_SOURCE_SHA256    @"' + t["sha256"] + '"',
        f"#define CPM_ANCHOR_RECORD_COUNT     {len(t['anchors'])}u",
        "",
        ("#define CPM_ANCHOR_HAS_CANVAS_RECT  1\n"
         "#define CPM_ANCHOR_CANVAS_RECT      CGRectMake(%g, %g, %g, %g)"
         % (float(t["canvas"].get("x", 0)), float(t["canvas"].get("y", 0)),
            float(t["canvas"].get("width", 0)), float(t["canvas"].get("height", 0))))
        if t.get("canvas") else
        "#define CPM_ANCHOR_HAS_CANVAS_RECT  0\n"
        "#define CPM_ANCHOR_CANVAS_RECT      CGRectZero",
        "",
        "static const CPMUIAnchorRecord CPMUIAnchorRecords[CPM_ANCHOR_RECORD_COUNT]",
        "    __attribute__((unused)) = {",
    ]
    for a in t["anchors"]:
        lines.append(
            "    { %s, %.3f, %.3f, %.3f, %.3f, %.3f, %.3f, %.3f, %.3f, %s, %s, \"%s\" },"
            % (
                ELEMENT_TYPES[a["type"]],
                a["cx"], a["cy"], a["w"], a["h"],
                a["minX"], a["maxX"], a["minY"], a["maxY"],
                "YES" if a["type"] in SLIDER_TYPES else "NO",
                "YES" if a["valid"] else "NO",
                a["name"].replace('"', "'"),
            )
        )
    lines += [
        "};",
        "",
        "NS_ASSUME_NONNULL_END",
        "",
        "#endif /* CPM_ANCHORS_DEFAULT_H */",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("mode", nargs="?", default="generate", choices=["generate", "check", "show"])
    args = ap.parse_args()

    if not JSON_PATH.exists():
        print(f"cpm_anchors: missing {JSON_PATH}", file=sys.stderr)
        return 2
    table = load()

    if args.mode == "show":
        print(json.dumps(table, indent=2))
        for name in table["missing"]:
            print(f"warning: no anchor for {name}", file=sys.stderr)
        return 0

    text = render(table)
    if args.mode == "check":
        if not OUT_PATH.exists():
            print(f"cpm_anchors: {OUT_PATH.name} is missing — run `make anchors`", file=sys.stderr)
            return 1
        if OUT_PATH.read_text() != text:
            print(f"cpm_anchors: {OUT_PATH.name} is stale vs {JSON_PATH.name} — run `make anchors`",
                  file=sys.stderr)
            return 1
        print("cpm_anchors: header matches the JSON")
        return 0

    OUT_PATH.write_text(text)
    print(f"cpm_anchors: wrote {OUT_PATH.relative_to(ROOT)} "
          f"({len(table['anchors'])} anchors, ref {table['refW']:g}x{table['refH']:g})")
    for name in table["missing"]:
        print(f"  warning: no anchor for {name}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
